random_number:
    path: /random/{limit}
    controller: Index\Controller\MicroController::randomNumber
admin:
    path: /admin/{uri}
    controller: App\Controller\MicroController::admin
    requirements:
        uri: .*